[package]
name = "thulp-workspace"
version.workspace = true
edition.workspace = true

[lib]
name = "thulp_workspace"
path = "src/lib.rs"

[dependencies]
thulp-core = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror.workspace = true
serde_json.workspace = true
